name: Send mail

on:
  push:
    branches:
      - main

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions job result
          to: 'rodrigo@hibrido.com.br'
          from: 'Luke Skywalker'
          body: 'Build job of ${{ github.repository }} completed successfully!'
          html_body: 'file://README.html'
          cc: 'kyloren@example.com,leia@example.com'
          bcc: 'r2d2@example.com,hansolo@example.com'
          reply_to: 'luke@example.com'
          in_reply_to: '<random-luke@example.com>'
          ignore_cert: true
          convert_markdown: true
          attachments: 'attachments.zip,git.diff,./dist/static/*.js'
          priority: low
